(function(g){var window=this;var eBa=function(a,b){return g.Vb(a,b)},K4=function(a){g.pn(a,"zx",g.tc());
return a},L4=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.sn(a.g,b,c)},fBa=function(a,b){var c=[];
g.$k(b,function(a){try{var b=g.RD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.QD(b)&&c.push(a):c.push(a)},a);
return c},gBa=function(a,b){var c=fBa(a,b);
(0,g.C)(c,function(a){g.RD.prototype.remove.call(this,a)},a)},hBa=function(a){if(a.Gd){if(a.Gd.locationOverrideToken)return{locationOverrideToken:a.Gd.locationOverrideToken};
if(null!=a.Gd.latitudeE7&&null!=a.Gd.longitudeE7)return{latitudeE7:a.Gd.latitudeE7,longitudeE7:a.Gd.longitudeE7}}return null},iBa=function(a,b,c,d){var e=new g.fn(null,void 0);
a&&g.gn(e,a);b&&g.hn(e,b);c&&g.jn(e,c);d&&g.kn(e,d);return e},M4=function(a,b){g.JE[a]=!0;
var c=g.HE();c&&c.publish.apply(c,arguments);g.JE[a]=!1},N4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.$m;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jBa(this,a.capabilities||""),kBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},jBa=function(a,b){a.capabilities.clear();
(0,g.ke)(b.split(","),g.La(eBa,lBa)).forEach(function(b){a.capabilities.add(b)})},kBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},O4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},P4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nBa=function(a){return new O4(a)},oBa=function(a){return g.Fa(a)?(0,g.I)(a,nBa):[]},Q4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},R4=function(a){return g.Fa(a)?"["+(0,g.I)(a,Q4).join(",")+"]":"null"},S4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},pBa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},T4=function(a,b){return g.Ra(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},U4=function(a,b){return g.Ra(a,function(a){return P4(a,b)})},qBa=function(){var a=(0,g.TH)();
a&&gBa(a,a.g.Wd(!0))},V4=function(){var a=g.WH("yt-remote-connected-devices")||[];
g.ob(a);return a},rBa=function(a){if(g.Wa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},sBa=function(a){g.VH("yt-remote-connected-devices",a,86400)},X4=function(){if(W4)return W4;
var a=g.WH("yt-remote-device-id");a||(a=S4(),g.VH("yt-remote-device-id",a,31536E3));for(var b=V4(),c=1,d=a;g.Va(b,d);)c++,d=a+"#"+c;return W4=d},Y4=function(){var a=V4(),b=X4();
g.Va(a,b);g.YH()&&g.qb(a,b);a=rBa(a);if(g.Wa(a))try{g.sH("remote_sid")}catch(c){}else try{g.rH("remote_sid",a.join(","),-1)}catch(c){}},tBa=function(){return g.WH("yt-remote-session-browser-channel")},uBa=function(){return g.WH("yt-remote-local-screens")||[]},vBa=function(){g.VH("yt-remote-lounge-token-expiration",!0,86400)},wBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(uBa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Om)(c,function(a){return!g.Va(b,a)})&&vBa();
g.VH("yt-remote-local-screens",a,31536E3)},xBa=function(a,b){g.VH("yt-remote-session-browser-channel",a);
g.VH("yt-remote-session-screen-id",b);var c=V4(),d=X4();g.Va(c,d)||c.push(d);sBa(c);Y4()},Z4=function(a){a||(g.XH("yt-remote-session-screen-id"),g.XH("yt-remote-session-video-id"));
Y4();a=V4();g.$a(a,X4());sBa(a)},yBa=function(){if(!$4){var a=g.bE();
a&&($4=new g.LD(a))}return $4?!!$4.get("yt-remote-use-staging-server"):!1},a5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},zBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},b5=function(a){a.length?ABa(a.shift(),function(){b5(a)}):c5()},BBa=function(a){return"chrome-extension://"+a+d5},ABa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},c5=function(){var a=zBa();
a&&a(!1,"No cast extension found")},DBa=function(){if(CBa){var a=2,b=zBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;ABa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",c5,c)}},EBa=function(){DBa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);b5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+d5,"//www.gstatic.com/eureka/clank"+d5])},e5=function(a,b,c){g.J.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.zd=b;this.B=(0,g.A)(this.lK,this);this.g=!1;this.l=0;this.o=this.Ga=null;this.A=[]},f5=function(){},g5=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.wn(this);this.l=new g.Lg;this.l.setInterval(250)},GBa=function(a,b,c){a.Bj=1;
a.qh=K4(b.clone());a.Ri=c;a.B=!0;FBa(a,null)},h5=function(a,b,c,d,e){a.Bj=1;
a.qh=K4(b.clone());a.Ri=null;a.B=c;e&&(a.hF=!1);FBa(a,d)},FBa=function(a,b){a.zk=(0,g.G)();
i5(a);a.Oh=a.qh.clone();L4(a.Oh,"t",a.C);a.yn=0;a.Tc=a.g.qt(a.g.mn()?b:null);0<a.cu&&(a.uq=new g.Jl((0,g.A)(a.vG,a,a.Tc),a.cu));a.W.U(a.Tc,"readystatechange",a.sU);var c=a.ri?g.cc(a.ri):{};a.Ri?(a.tr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Tc.send(a.Oh,a.tr,a.Ri,c)):(a.tr="GET",a.hF&&!g.Zd&&(c.Connection="close"),a.Tc.send(a.Oh,a.tr,null,c));a.g.uf(1)},JBa=function(a,b,c){for(var d=!0;!a.Zh&&a.yn<c.length;){var e=HBa(a,c);
if(e==j5){4==b&&(a.rh=4,k5(15),d=!1);break}else if(e==IBa){a.rh=4;k5(16);d=!1;break}else l5(a,e)}4==b&&0==c.length&&(a.rh=1,k5(17),d=!1);a.Af=a.Af&&d;d||(m5(a),n5(a))},HBa=function(a,b){var c=a.yn,d=b.indexOf("\n",c);
if(-1==d)return j5;c=Number(b.substring(c,d));if(isNaN(c))return IBa;d+=1;if(d+c>b.length)return j5;var e=b.substr(d,c);a.yn=d+c;return e},LBa=function(a,b){a.zk=(0,g.G)();
i5(a);var c=b?window.location.hostname:"";a.Oh=a.qh.clone();g.pn(a.Oh,"DOMAIN",c);g.pn(a.Oh,"t",a.C);try{a.Bf=new ActiveXObject("htmlfile")}catch(n){m5(a);a.rh=7;k5(22);n5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in o5)k=o5[l];else if(l in KBa)k=o5[l]=KBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
o5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Dd(g.Rc("b/12014412"),d+"</body></html>");a.Bf.open();a.Bf.write(g.sd(c));a.Bf.close();a.Bf.parentWindow.m=(0,g.A)(a.vT,a);a.Bf.parentWindow.d=(0,g.A)(a.sE,a,!0);a.Bf.parentWindow.rpcClose=(0,g.A)(a.sE,a,!1);c=a.Bf.createElement("DIV");a.Bf.parentWindow.document.body.appendChild(c);d=g.fd(a.Oh.toString());d=g.oc(g.bd(d));d=g.Dd(g.Rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.zd(c,g.sd(d));a.g.uf(1)},i5=function(a){a.Ox=(0,g.G)()+
a.A;
MBa(a,a.A)},MBa=function(a,b){if(null!=a.Tk)throw Error("WatchDog timer not null");
a.Tk=p5((0,g.A)(a.KT,a),b)},q5=function(a){a.Tk&&(g.v.clearTimeout(a.Tk),a.Tk=null)},n5=function(a){a.g.eB()||a.Zh||a.g.bq(a)},m5=function(a){q5(a);
g.yf(a.uq);a.uq=null;a.l.stop();g.Cn(a.W);if(a.Tc){var b=a.Tc;a.Tc=null;b.abort();b.dispose()}a.Bf&&(a.Bf=null)},l5=function(a,b){try{a.g.lE(a,b),a.g.uf(4)}catch(c){}},OBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;NBa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){OBa(a,b,c,d,f)},f)})}},NBa=function(a,b,c){var d=new Image;
d.onload=function(){try{r5(d),c(!0)}catch(e){}};
d.onerror=function(){try{r5(d),c(!1)}catch(e){}};
d.onabort=function(){try{r5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{r5(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},r5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},PBa=function(a){this.g=a;
this.l=new f5},QBa=function(a){var b=s5(a.g,a.pl,"/mail/images/cleardot.gif");
K4(b);OBa(b.toString(),5E3,(0,g.A)(a.tJ,a),3,2E3);a.uf(1)},u5=function(a){var b=a.g.H;
if(null!=b)k5(5),b?(k5(11),t5(a.g,a,!1)):(k5(12),t5(a.g,a,!0));else if(a.ye=new g5(a,void 0,void 0,void 0),a.ye.ri=a.Zt,b=a.g,b=s5(b,b.mn()?a.Zl:null,a.au),k5(5),!g.Xd||g.Kc(10))L4(b,"TYPE","xmlhttp"),h5(a.ye,b,!1,a.Zl,!1);else{L4(b,"TYPE","html");var c=a.ye;a=!!a.Zl;c.Bj=3;c.qh=K4(b.clone());LBa(c,a)}},v5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new f5;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},RBa=function(a,b){this.g=a;
this.map=b;this.context=null},SBa=function(a){g.Af.call(this,"statevent",a)},TBa=function(a,b){g.Af.call(this,"timingevent",a);
this.size=b},UBa=function(a){g.Af.call(this,"serverreachability",a)},XBa=function(a){VBa(a);
if(3==a.g){var b=a.Tm++,c=a.Fo.clone();g.pn(c,"SID",a.o);g.pn(c,"RID",b);g.pn(c,"TYPE","terminate");w5(a,c);b=new g5(a,a.o,b,void 0);b.Bj=2;b.qh=K4(c.clone());(new Image).src=b.qh;b.zk=(0,g.G)();i5(b)}WBa(a)},YBa=function(a){a.QJ(1,0);
a.Fo=s5(a,null,a.Yt);x5(a)},VBa=function(a){a.eh&&(a.eh.abort(),a.eh=null);
a.xc&&(a.xc.cancel(),a.xc=null);a.tg&&(g.v.clearTimeout(a.tg),a.tg=null);y5(a);a.ce&&(a.ce.cancel(),a.ce=null);a.kh&&(g.v.clearTimeout(a.kh),a.kh=null)},ZBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new RBa(a.lP++,b));2!=a.g&&3!=a.g||x5(a)},x5=function(a){a.ce||a.kh||(a.kh=p5((0,g.A)(a.rE,a),0),a.tj=0)},aCa=function(a,b){if(1==a.g){if(!b){a.Tm=Math.floor(1E5*Math.random());
var c=a.Tm++,d=new g5(a,"",c,void 0);d.ri=null;var e=z5(a),f=a.Fo.clone();g.pn(f,"RID",c);g.pn(f,"CVER","1");w5(a,f);GBa(d,f,e);a.ce=d;a.g=2}}else 3==a.g&&(b?$Ba(a,b):0==a.l.length||a.ce||$Ba(a))},$Ba=function(a,b){if(b)if(6<a.ci){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Tm-1;var d=z5(a)}else c=b.D,d=b.Ri;else c=a.Tm++,d=z5(a);var e=a.Fo.clone();g.pn(e,"SID",a.o);g.pn(e,"RID",c);g.pn(e,"AID",a.Uj);w5(a,e);c=new g5(a,a.o,c,a.tj+1);c.ri=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ce=c;GBa(c,e,d)},w5=function(a,b){if(a.yd){var c=a.yd.KA();
c&&g.Kb(c,function(a,c){g.pn(b,c,a)})}},z5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.ci&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.ci?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},bCa=function(a){a.xc||a.tg||(a.D=1,a.tg=p5((0,g.A)(a.qE,a),0),a.lj=0)},A5=function(a){if(a.xc||a.tg||3<=a.lj)return!1;
a.D++;a.tg=p5((0,g.A)(a.qE,a),cCa(a,a.lj));a.lj++;return!0},t5=function(a,b,c){a.qr=c;
a.Jf=b.Fg;a.C||YBa(a)},y5=function(a){null!=a.fi&&(g.v.clearTimeout(a.fi),a.fi=null)},cCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},B5=function(a,b){if(2==b||9==b){var c=null;
a.yd&&(c=null);var d=(0,g.A)(a.jV,a);c||(c=new g.fn("//www.google.com/images/cleardot.gif"),K4(c));NBa(c.toString(),1E4,d)}else k5(2);dCa(a,b)},dCa=function(a,b){a.g=0;
a.yd&&a.yd.Jz(b);WBa(a);VBa(a)},WBa=function(a){a.g=0;
a.Jf=-1;if(a.yd)if(0==a.A.length&&0==a.l.length)a.yd.Ts();else{g.db(a.A);var b=g.db(a.l);a.A.length=0;a.l.length=0;a.yd.Ts(b)}},s5=function(a,b,c){var d=g.qn(c);
if(""!=d.l)b&&g.hn(d,b+"."+d.l),g.jn(d,d.B);else{var e=window.location;d=iBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.El&&g.Kb(a.El,function(a,b){g.pn(d,b,a)});
g.pn(d,"VER",a.ci);w5(a,d);return d},p5=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},k5=function(a){C5.dispatchEvent(new SBa(C5,a))},eCa=function(){},fCa=function(a,b){this.action=a;
this.params=b||{}},D5=function(a,b){g.J.call(this);
this.g=new g.U(this.lT,0,this);g.K(this,this.g);this.zd=5E3;this.l=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},E5=function(a,b,c){this.I=a;
this.C=b;this.o=new g.KD;this.l=new D5(this.LV,this);this.g=this.fb=null;this.zb=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.J=c||!1},gCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.qr,sessionId:a.g.o,arrayId:a.g.Uj}},hCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&aCa(a.g),XBa(a.g));a.F=0},F5=function(a){return!!a.g&&3==a.g.g},iCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},G5=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||document.location.href;var b=g.$g(a)||"";b&&(this.port=":"+b);this.domain=g.Zg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.l=!1))},H5=function(a,b){var c=a.g;
if(g.za(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.gh(c+b,{})},I5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.A,d,!0),onError:g.La(a.o,e),Dd:g.La(a.B,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.pF(b,a)},mCa=function(){var a=jCa;
kCa();J5.push(a);lCa(J5)},K5=function(a,b){kCa();
var c=J5,d=nCa(a,String(b));g.Wa(c)?oCa(d):(lCa(c),(0,g.C)(c,function(a){a(d)}))},kCa=function(){J5||(J5=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",J5,void 0))},oCa=function(a){var b=(L5+1)%50;
L5=b;M5[b]=a;N5||(N5=49==b)},lCa=function(a){var b=M5;
if(b[0]){var c=L5,d=N5?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
M5=Array(50);L5=-1;N5=!1}},nCa=function(a,b){var c=((0,g.G)()-pCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O5=function(a){g.V.call(this);
this.D=a;this.g=[]},qCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},rCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.ke)(a.g,function(a){return!!T4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=qCa(a,b[d])||c;return c},sCa=function(a,b){var c=a.g.length;
a.g=(0,g.ke)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},P5=function(a,b,c,d){g.V.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ga=NaN},R5=function(a){O5.call(this,"LocalScreenService");
this.o=a;this.l=NaN;Q5(this);this.info("Initializing with "+R4(this.g))},tCa=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=H5(a.o,"/pairing/get_lounge_token_batch");
I5(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.zK,a),(0,g.A)(a.yK,a))}},Q5=function(a){var b=oBa(uBa());
b=(0,g.ke)(b,function(a){return!a.uuid});
return rCa(a,b)},S5=function(a,b){wBa((0,g.I)(a.g,mBa));
b&&vBa()},U5=function(a,b){g.V.call(this);
this.C=b;var c=g.WH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Va(c,l)}this.g=d;this.B=a;this.o=this.A=NaN;this.l=null;T5("Initialized with "+g.Rg(this.g))},uCa=function(a,b,c){var d=H5(a.B,"/pairing/get_screen_availability");
I5(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},V5=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T5("Updated online screens: "+g.Rg(a.g)),a.g=b,a.T("screenChange"));vCa(a)},W5=function(a){isNaN(a.o)||g.GE(a.o);
a.o=g.EE((0,g.A)(a.Jw,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},T5=function(a){K5("OnlineScreenService",a)},wCa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.oc("Requesting availability of screen w/o lounge token.")});
return b},vCa=function(a){a=g.Sb(g.Lb(a.g,function(a){return a}));
g.ob(a);a.length?g.VH("yt-remote-online-screen-ids",a.join(","),60):g.XH("yt-remote-online-screen-ids")},X5=function(a){O5.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};xCa(this)},zCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.re();if(k=(c?U4(k,c):null)||U4(k,b)){k.uuid=b;var l=Y5(a,k);uCa(a.l,l,function(a){e(a?l:null)})}else c?yCa(a,c,(0,g.A)(function(a){var f=Y5(this,new O4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));uCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},ACa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},yCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.pF(H5(a.C,"/pairing/get_lounge_token_batch"),e)},BCa=function(a){a.g=a.o.re();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+R4(a.g))},xCa=function(a){Z5(a);
a.o=new R5(a.C);a.o.subscribe("screenChange",(0,g.A)(a.MK,a));BCa(a);a.A=oBa(g.WH("yt-remote-automatic-screen-cache")||[]);Z5(a);a.info("Initializing automatic screens: "+R4(a.A));a.l=new U5(a.C,(0,g.A)(a.re,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.T("onlineScreenChange")},a))},Y5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=U4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.VH("yt-remote-automatic-screen-cache",(0,g.I)(a.A,mBa)));Z5(a);a.B[b.uuid]=b.id;g.VH("yt-remote-device-id-map",a.B,31536E3);return b},Z5=function(a){a.B=g.WH("yt-remote-device-id-map")||{}},$5=function(a,b,c){g.V.call(this);
this.O=c;this.H=a;this.l=b;this.o=null},a6=function(a,b){K5(a.O,b)},b6=function(a,b){$5.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.RV,this);this.B=(0,g.A)(this.ZT,this);this.A=g.EE((0,g.A)(function(){CCa(this,null)},this),12E4)},DCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Rg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.A)(function(){a6(this,"Failed to send message: getMdxSessionStatus.")},a)):a6(a,"Sending yt message without session: "+g.Rg(b))},CCa=function(a,b){g.GE(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.cq,a),d=(0,g.A)(a.xe,a);a.VA(b,c,d,5)}}else a.xe(Error("Waiting for session status timed out."))},c6=function(a,b,c){$5.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.L=c;this.B=null;this.D=g.y;this.C=NaN;this.J=(0,g.A)(this.UV,this);this.g=g.y},ECa=function(a){a.g=a.H.zG(a.I,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.y;
this.cq(a)},a),(0,g.A)(function(a){this.g=g.y;
this.xe(a)},a))},FCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.L;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}yBa()&&(b.env_useStageMdx=1);return g.fh(b)},d6=function(a,b){$5.call(this,a,b,"ManualSession");
this.g=g.EE((0,g.A)(this.Wj,this,null),150)},e6=function(a,b,c,d){g.V.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.wS,this)},GCa=function(a,b){return b?g.Ra(a.o,function(a){return P4(b,a.label)},a):null},f6=function(a){K5("Controller",a)},jCa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},g6=function(a){return a.B||!!a.o.length||!!a.g},h6=function(a,b,c){b!=a.g&&(g.yf(a.g),(a.g=b)?(c?a.T("yt-remote-cast2-receiver-resumed",b.l):a.T("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.oE,a,b)),b.o?a.T("yt-remote-cast2-session-change",b.o):c&&a.g.Wj(null)):a.T("yt-remote-cast2-session-change",null))},HCa=function(a){var b=a.l.yG(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&P4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=GCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},NCa=function(a,b,c,d,e,f,k){ICa()?JCa(b,e,f,k)&&(j6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?KCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?KCa(a,c):(k6("Failed to load cast API: "+d),l6(!1),j6(!1),g.XH("yt-remote-cast-available"),g.XH("yt-remote-cast-receiver"),LCa(),c(!1))},d?g.RE("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?EBa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?c5():(DBa(),b5(MCa.map(BBa))))):i6("Cannot initialize because not running Chrome")},LCa=function(){i6("dispose");
var a=m6();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);OCa(!1);g.ME(n6);n6.length=0},o6=function(){return!!g.WH("yt-remote-cast-installed")},PCa=function(){var a=g.WH("yt-remote-cast-receiver");
return a?a.friendlyName:null},QCa=function(){i6("clearCurrentReceiver");
g.XH("yt-remote-cast-receiver")},RCa=function(){return o6()?m6()?m6().getCastSession():(k6("getCastSelector: Cast is not initialized."),null):(k6("getCastSelector: Cast API is not installed!"),null)},q6=function(){o6()?m6()?p6()?(i6("Requesting cast selector."),m6().requestSession()):(i6("Wait for cast API to be ready to request the session."),n6.push(g.LE("yt-remote-cast2-api-ready",q6))):k6("requestCastSelector: Cast is not initialized."):k6("requestCastSelector: Cast API is not installed!")},r6=
function(a,b){p6()?m6().setConnectedScreenStatus(a,b):k6("setConnectedScreenStatus called before ready.")},ICa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.tL||a},SCa=function(a,b){m6().init(a,b)},JCa=function(a,b,c,d){var e=!1;
m6()||(a=new e6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.VH("yt-remote-cast-available",a);M4("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i6("onReceiverSelected: "+a.friendlyName);
g.VH("yt-remote-cast-receiver",a);M4("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i6("onReceiverResumed: "+a.friendlyName);
g.VH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i6("onSessionChange: "+Q4(a));
a||g.XH("yt-remote-cast-receiver");M4("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
i6("cloudview.createSingleton_: "+e);return e},m6=function(){return g.w("yt.mdx.remote.cloudview.instance_")},KCa=function(a,b){l6(!0);
j6(!1);SCa(a,function(a){a?(OCa(!0),g.OE("yt-remote-cast2-api-ready")):(k6("Failed to initialize cast API."),l6(!1),g.XH("yt-remote-cast-available"),g.XH("yt-remote-cast-receiver"),LCa());b(a)})},i6=function(a){K5("cloudview",a)},k6=function(a){K5("cloudview",a)},l6=function(a){i6("setCastInstalled_ "+a);
g.VH("yt-remote-cast-installed",a)},p6=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},OCa=function(a){i6("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},j6=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},s6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.D=0;this.g=null;this.hasNext=this.Nf=!1;this.H=this.F=this.l=this.A=0;this.o=NaN;this.B=!1;this.reset(a)},t6=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Nf=!1;a.hasNext=!1;a.D=0;a.C=(0,g.G)();a.A=0;a.l=0;a.F=0;a.H=0;a.o=NaN;a.B=!1},u6=function(a){return a.rb()?((0,g.G)()-a.C)/1E3:0},v6=function(a,b){a.D=b;
a.C=(0,g.G)()},w6=function(a){switch(a.playerState){case 1:case 1081:return((0,g.G)()-a.C)/1E3+a.D;
case -1E3:return 0}return a.D},x6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&t6(a)},y6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Nf;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.l;b.duration=a.F;b.loadedTime=a.H;b.liveIngestionTime=a.o;return b},A6=function(a,b){g.V.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.aD;this.o=this.l=null;this.H=(0,g.A)(this.WP,this);this.D=(0,g.A)(this.Wm,this);this.F=(0,g.A)(this.VP,this);this.I=(0,g.A)(this.iQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Wx,this),TCa(this))):c=3;0!=c&&(b?this.Wx(c):g.EE((0,g.A)(function(){this.Wx(c)},this),0));
var d=RCa();d&&z6(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},B6=function(a){return new s6(a.A.getPlayerContextData())},TCa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.La(this.rS,a),this))},a)},UCa=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C6=function(a,b){50>a.B.Pc()&&g.cD(a.B,b)},E6=function(a,b,c){var d=B6(a);
v6(d,c);-1E3!=d.playerState&&(d.playerState=b);D6(a,d)},F6=function(a,b,c){a.A.sendMessage(b,c)},D6=function(a,b){UCa(a);
a.A.setPlayerContextData(y6(b));TCa(a)},z6=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Wm(null));
a.o=b;a.o&&(K5("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Wm(a.o.media[0]))},VCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=B6(a);b.contentId!=d.videoId&&K5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;v6(d,a.l.getEstimatedTime());D6(a,d)}else K5("CP","No cast media video. Ignoring state update.")},G6=function(a,b,c){return(0,g.A)(function(a){this.oc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.oc("Retrying "+b+" using MDx browser channel."),F6(this,b,c))},a)},H6=function(a,b,c){g.V.call(this);
this.B=NaN;this.L=!1;this.I=this.H=this.J=this.O=NaN;this.R=[];this.A=this.D=this.o=this.gb=this.g=null;this.ra=a;this.R.push(g.rG(window,"beforeunload",(0,g.A)(this.pK,this)));this.l=[];this.gb=new s6;this.Y=b.id;this.g=WCa(this,c);this.g.subscribe("handlerOpened",this.aQ,this);this.g.subscribe("handlerClosed",this.XP,this);this.g.subscribe("handlerError",this.YP,this);this.g.subscribe("handlerMessage",this.ZP,this);iCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=this.gb.videoId;
g.YH()&&g.VH("yt-remote-session-video-id",a)},this)},I6=function(a){K5("conn",a)},WCa=function(a,b){return new E5(H5(a.ra,"/bc"),b)},J6=function(a,b){a.T("proxyStateChange",b)},XCa=function(a){a.B=g.EE((0,g.A)(function(){I6("Connecting timeout");
this.C(1)},a),2E4)},K6=function(a){g.GE(a.B);
a.B=NaN},L6=function(a){g.GE(a.O);
a.O=NaN},YCa=function(a){M6(a);
a.J=g.EE((0,g.A)(function(){N6(this,"getNowPlaying")},a),2E4)},M6=function(a){g.GE(a.J);
a.J=NaN},$Ca=function(a,b){b&&(K6(a),L6(a));
b==(F5(a.g)&&isNaN(a.B))?b&&(J6(a,1),N6(a,"getSubtitlesTrack")):b?(a.X()&&a.gb.reset(),J6(a,1),N6(a,"getNowPlaying"),ZCa(a)):a.C(1)},aDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.gb.videoId&&(g.Yb(b.params)?a.gb.g=null:a.gb.g=b.params,a.T("remotePlayerChange"))},bDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.gb.listId=b.params.listId||a.gb.listId;x6(a.gb,c,d);a.T("remoteQueueChange")},dDa=function(a,b){b.params=b.params||{};
bDa(a,b);cDa(a,b);a.T("autoplayDismissed")},cDa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
v6(a.gb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.gb.playerState&&(c=-1E3);a.gb.playerState=c;c=Number(b.params.loadedTime);a.gb.H=isNaN(c)?0:c;c=Number(b.params.duration);a.gb.F=isNaN(c)?0:c;c=a.gb;var d=Number(b.params.liveIngestionTime);c.o=d;c.B=isNaN(d)?!1:!0;c=a.gb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.gb.playerState?YCa(a):M6(a);a.T("remotePlayerChange")},eDa=function(a,b){if(-1E3!=
a.gb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.gb.playerState=c;c=parseInt(b.params.currentTime,10);v6(a.gb,isNaN(c)?0:c);a.T("remotePlayerChange")}},fDa=function(a,b){var c="true"==b.params.muted;
a.gb.volume=parseInt(b.params.volume,10);a.gb.muted=c;a.T("remotePlayerChange")},gDa=function(a,b){a.D=b.params.videoId;
a.T("nowAutoplaying",parseInt(b.params.timeout,10))},hDa=function(a,b){var c="true"==b.params.hasNext;
a.gb.Nf="true"==b.params.hasPrevious;a.gb.hasNext=c;a.T("previousNextChange")},ZCa=function(a){g.GE(a.I);
a.I=g.EE((0,g.A)(a.C,a,1),864E5)},N6=function(a,b,c){c?I6("Sending: action="+b+", params="+g.Rg(c)):I6("Sending: action="+b);
a.g.sendMessage(b,c)},O6=function(a){O5.call(this,"ScreenServiceProxy");
this.hd=a;this.l=[];this.l.push(this.hd.$_s("screenChange",(0,g.A)(this.PV,this)));this.l.push(this.hd.$_s("onlineScreenChange",(0,g.A)(this.RR,this)))},mDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.wE("MDX_CONFIG")||b;qBa();Y4();P6||(P6=new G5(b?b.loungeApiHost:void 0),yBa()&&(P6.g="/api/loungedev"));Q6||(Q6=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",Q6,void 0));iDa();var c=R6();if(!c){var d=new X5(P6);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=R6();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);NCa(a,d,function(a){a?S6()&&r6(S6(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){M4("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),T6("Initializing: "+g.Rg(b)),U6.push(g.LE("yt-remote-cast2-availability-change",function(){M4("yt-remote-receiver-availability-change")})),U6.push(g.LE("yt-remote-cast2-receiver-selected",function(){V6(null);
M4("yt-remote-auto-connect","cast-selector-receiver")})),U6.push(g.LE("yt-remote-cast2-receiver-resumed",function(){M4("yt-remote-receiver-resumed","cast-selector-receiver")})),U6.push(g.LE("yt-remote-cast2-session-change",jDa)),U6.push(g.LE("yt-remote-connection-change",function(a){a?r6(S6(),"YouTube TV"):W6()||(r6(null,null),QCa())})),a=X6(),b.isAuto&&(a.id+="#dial"),g.ZE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T6(" -- with channel params: "+
g.Rg(a)),kDa(a),c.start(),S6()||lDa())},oDa=function(){var a=nDa();
o6()&&g.WH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},nDa=function(){var a=R6().hd.$_gos();
var b=Y6();b&&Z6()&&(T4(a,b)||a.push(b));return pBa(a)},$6=function(){var a=pDa();
!a&&o6()&&PCa()&&(a={key:"cast-selector-receiver",name:PCa()});return a},pDa=function(){var a=nDa(),b=Y6();
b||(b=W6());return g.Ra(a,function(a){return b&&P4(b,a.key)?!0:!1})},Y6=function(){var a=S6();
if(!a)return null;var b=R6().re();return U4(b,a)},jDa=function(a){T6("remote.onCastSessionChange_: "+Q4(a));
if(a){var b=Y6();b&&b.id==a.id?r6(b.id,"YouTube TV"):(b&&a7(),b7(a,1))}else Z6()&&a7()},a7=function(){p6()?m6().stopSession():k6("stopSession called before API ready.");
var a=Z6();a&&(a.disconnect(1),c7(null))},d7=function(){var a=Z6();
return!!a&&3!=a.getProxyState()},T6=function(a){K5("remote",a)},R6=function(){if(!e7){var a=g.w("yt.mdx.remote.screenService_");
e7=a?new O6(a):null}return e7},S6=function(){return g.w("yt.mdx.remote.currentScreenId_")},qDa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},rDa=function(){return g.w("yt.mdx.remote.connectData_")},V6=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},Z6=function(){return g.w("yt.mdx.remote.connection_")},c7=function(a){var b=Z6();
V6(null);a||qDa("");g.Ca("yt.mdx.remote.connection_",a,void 0);Q6&&((0,g.C)(Q6,function(b){b(a)}),Q6.length=0);
b&&!a?M4("yt-remote-connection-change",!1):!b&&a&&M4("yt-remote-connection-change",!0)},W6=function(){var a=g.YH();
if(!a)return null;var b=R6().re();return U4(b,a)},b7=function(a,b){Y6()&&Y6();
qDa(a.id);var c=new H6(P6,a,X6());c.connect(b,rDa());c.subscribe("beforeDisconnect",function(a){M4("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Z6()&&c7(null)});
c7(c)},lDa=function(){var a=W6();
a?(T6("Resume connection to: "+Q4(a)),b7(a,0)):(Z4(),QCa(),T6("Skipping connecting because no session screen found."))},iDa=function(){var a=X6();
if(g.Yb(a)){a=X4();var b=g.WH("yt-remote-session-name")||"",c=g.WH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},X6=function(){return g.w("yt.mdx.remote.channelParams_")||{}},kDa=function(a){a?(g.VH("yt-remote-session-app",a.app),g.VH("yt-remote-session-name",a.name)):(g.XH("yt-remote-session-app"),g.XH("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},f7=function(a,b,c){g.J.call(this);
this.B=a;this.l=b;this.o=new g.GG(this);g.K(this,this.o);this.o.N(b,"onCaptionsTrackListChanged",this.lR);this.o.N(b,"captionschanged",this.UP);this.o.N(b,"captionssettingschanged",this.PF);this.o.N(b,"videoplayerreset",this.eq);this.o.N(b,"mdxautoplaycancel",this.sJ);this.R=this.o.N(b,"onVolumeChange",this.VD);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.kE,this);c.subscribe("remotePlayerChange",this.Zm,this);c.subscribe("remoteQueueChange",this.eq,this);c.subscribe("autoplayUpNext",this.HD,
this);c.subscribe("previousNextChange",this.hE,this);c.subscribe("nowAutoplaying",this.ZD,this);c.subscribe("autoplayDismissed",this.GD,this);this.suggestion=null;this.H=new g.mR(64);this.A=new g.U(this.MF,500,this);g.K(this,this.A);this.C=new g.U(this.NF,1E3,this);g.K(this,this.C);this.J=new e5(this.tV,0,this);g.K(this,this.J);this.D={};this.O=new g.U(this.nG,1E3,this);g.K(this,this.O);this.I=new g.Jl(this.ON,1E3,this);g.K(this,this.I);this.L=g.y;this.PF();this.eq();this.Zm()},g7=function(a,b){a.B.Be(b,
a.l.getVideoData().lengthSeconds)},sDa=function(a){g7(a,0);
a.A.stop();h7(a,new g.mR(64))},j7=function(a,b){if(i7(a)&&!a.F){var c=null;
b&&(c={style:a.l.getSubtitlesUserSettings()},g.fc(c,b));a.g.zF(a.l.getVideoData(1).videoId,c);a.D=B6(a.g).g}},k7=function(a,b){var c=a.l.getPlaylist();
if(c){var d=c.qe();var e=c.listId.toString()}c=a.l.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Mj,hBa(c));h7(a,new g.mR(1))},tDa=function(a,b){if(b){var c=a.l.getOption("captions","tracklist",{K3:1});
c&&c.length?(a.l.setOption("captions","track",b),a.F=!1):(a.l.loadModule("captions"),a.F=!0)}else a.l.setOption("captions","track",{})},i7=function(a){return B6(a.g).videoId==a.l.getVideoData(1).videoId},h7=function(a,b){a.C.stop();
var c=a.H;if(!g.sR(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.xV(a.l,d);a.H=b;uDa(a.B,c,b)}},l7=function(a){g.W.call(this,{G:"div",
K:"ytp-remote",M:[{G:"div",K:"ytp-remote-display-status",M:[{G:"div",K:"ytp-remote-display-status-icon",M:[g.gra()]},{G:"div",K:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.o=new g.lW(this,250);g.K(this,this.o);this.A=a;this.N(a,"presentingplayerstatechange",this.B);vDa(this,g.tV(a))},vDa=function(a,b){if(3==a.A.getPresentingPlayerType()){var c={RECEIVER_NAME:a.A.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.eW("\u5728$RECEIVER_NAME\u4e0a\u51fa\u73b0\u9519\u8bef",c):b.rb()||g.X(b,4)?g.eW("\u6b63\u5728$RECEIVER_NAME\u4e0a\u64ad\u653e",c):g.eW("\u5df2\u8fde\u63a5\u5230$RECEIVER_NAME",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},m7=function(a,b){g.VW.call(this,"\u64ad\u653e\u8bbe\u5907",0,a,b);
this.o=a;this.H={};this.N(a,"onMdxReceiversChange",this.J);this.N(a,"presentingplayerstatechange",this.J);this.J()},n7=function(a){g.PV.call(this,a);
this.l={key:S4(),name:"\u6b64\u8ba1\u7b97\u673a"};this.A=null;this.B=[];this.D=this.g=null;this.C=[this.l];this.o=this.l;this.Lm=new g.mR(64);this.H=0;this.F=-1;if(!g.rN(g.Y(this.player))){a=this.player;var b=g.LQ(a);b&&(b=b.Qp())&&(b=new m7(a,b),g.K(this,b));b=new l7(a);g.K(this,b);g.HV(a,b.element,4)}},uDa=function(a,b,c){a.Lm=c;
a.player.T("presentingplayerstatechange",new g.xR(c,b))},o7=function(a,b){if(b.key!=a.o.key)if(b.key==a.l.key)a7();
else{a.o=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ea(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Mj,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=hBa(d))&&(c.locationInfo=d);d=c}else d=null;T6("Connecting to: "+g.Rg(b));"cast-selector-receiver"==b.key?
(V6(d||null),p6()?m6().setLaunchParams(d||null):k6("setLaunchParams called before ready.")):!d&&d7()&&S6()==b.key?M4("yt-remote-connection-change",!0):(a7(),V6(d||null),d=R6().re(),(d=U4(d,b.key))&&b7(d,1))}},KBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},o5={"'":"\\'"},wDa={},lBa={oX:"atp",N1:"ska",b1:"que",q0:"mus",J1:"sus",AZ:"dsp",t1:"seq"};
N4.prototype.fh=function(){var a=new N4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var $4,W4="",d5=a5("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",CBa=a5("loadCastFramework")||a5("loadCastApplicationFramework"),MCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(e5,g.J);g.h=e5.prototype;g.h.kK=function(a){this.A=arguments;this.g=!1;this.Ga?this.o=(0,g.G)()+this.zd:this.Ga=g.Mg(this.B,this.zd)};
g.h.stop=function(){this.Ga&&(g.Ng(this.Ga),this.Ga=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();e5.ea.V.call(this)};
g.h.lK=function(){this.o?(this.Ga=g.Mg(this.B,this.o-(0,g.G)()),this.o=null):(this.Ga=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};f5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
f5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=g5.prototype;g.h.ri=null;g.h.Af=!1;g.h.Tk=null;g.h.Ox=null;g.h.zk=null;g.h.Bj=null;g.h.qh=null;g.h.Oh=null;g.h.Ri=null;g.h.Tc=null;g.h.yn=0;g.h.Bf=null;g.h.tr=null;g.h.rh=null;g.h.dm=-1;g.h.hF=!0;g.h.Zh=!1;g.h.cu=0;g.h.uq=null;var IBa={},j5={};g.h=g5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.sU=function(a){a=a.target;var b=this.uq;b&&3==g.Wx(a)?b.Wl():this.vG(a)};
g.h.vG=function(a){try{if(a==this.Tc)a:{var b=g.Wx(this.Tc),c=this.Tc.l,d=this.Tc.getStatus();if(g.Xd&&!g.Kc(10)||g.Zd&&!g.Jc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Cf&&!g.$x(this.Tc))break a;this.Zh||4!=b||7==c||(8==c||0>=d?this.g.uf(3):this.g.uf(2));q5(this);var e=this.Tc.getStatus();this.dm=e;var f=g.$x(this.Tc);(this.Af=200==e)?(4==b&&m5(this),this.B?(JBa(this,b,f),g.Cf&&this.Af&&3==b&&(this.W.U(this.l,"tick",this.nU),this.l.start())):l5(this,f),this.Af&&!this.Zh&&(4==b?this.g.bq(this):
(this.Af=!1,i5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rh=3,k5(13)):(this.rh=0,k5(14)),m5(this),n5(this))}}catch(k){this.Tc&&g.$x(this.Tc)}finally{}};
g.h.nU=function(){var a=g.Wx(this.Tc),b=g.$x(this.Tc);this.yn<b.length&&(q5(this),JBa(this,a,b),this.Af&&4!=a&&i5(this))};
g.h.vT=function(a){p5((0,g.A)(this.uT,this,a),0)};
g.h.uT=function(a){this.Zh||(q5(this),l5(this,a),i5(this))};
g.h.sE=function(a){p5((0,g.A)(this.tT,this,a),0)};
g.h.tT=function(a){this.Zh||(m5(this),this.Af=a,this.g.bq(this),this.g.uf(4))};
g.h.cancel=function(){this.Zh=!0;m5(this)};
g.h.KT=function(){this.Tk=null;var a=(0,g.G)();0<=a-this.Ox?(2!=this.Bj&&this.g.uf(3),m5(this),this.rh=2,k5(18),n5(this)):MBa(this,this.Ox-a)};
g.h.getLastError=function(){return this.rh};g.h=PBa.prototype;g.h.Zt=null;g.h.ye=null;g.h.wq=!1;g.h.fB=null;g.h.Do=null;g.h.av=null;g.h.au=null;g.h.Se=null;g.h.Fg=-1;g.h.Zl=null;g.h.pl=null;g.h.connect=function(a){this.au=a;a=s5(this.g,null,this.au);k5(3);this.fB=(0,g.G)();var b=this.g.F;null!=b?(this.Zl=b[0],(this.pl=b[1])?(this.Se=1,QBa(this)):(this.Se=2,u5(this))):(L4(a,"MODE","init"),this.ye=new g5(this,void 0,void 0,void 0),this.ye.ri=this.Zt,h5(this.ye,a,!1,null,!0),this.Se=0)};
g.h.tJ=function(a){if(a)this.Se=2,u5(this);else{k5(4);var b=this.g;b.Jf=b.eh.Fg;B5(b,9)}a&&this.uf(2)};
g.h.qt=function(a){return this.g.qt(a)};
g.h.abort=function(){this.ye&&(this.ye.cancel(),this.ye=null);this.Fg=-1};
g.h.eB=function(){return!1};
g.h.lE=function(a,b){this.Fg=a.dm;if(0==this.Se)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Jf=this.Fg;B5(c,2);return}this.Zl=c[0];this.pl=c[1]}else c=this.g,c.Jf=this.Fg,B5(c,2);else if(2==this.Se)if(this.wq)k5(7),this.av=(0,g.G)();else if("11111"==b){if(k5(6),this.wq=!0,this.Do=(0,g.G)(),c=this.Do-this.fB,!g.Xd||g.Kc(10)||500>c)this.Fg=200,this.ye.cancel(),k5(12),t5(this.g,this,!0)}else k5(8),this.Do=this.av=(0,g.G)(),this.wq=!1};
g.h.bq=function(){this.Fg=this.ye.dm;if(this.ye.Af)0==this.Se?this.pl?(this.Se=1,QBa(this)):(this.Se=2,u5(this)):2==this.Se&&((!g.Xd||g.Kc(10)?!this.wq:200>this.av-this.Do)?(k5(11),t5(this.g,this,!1)):(k5(12),t5(this.g,this,!0)));else{0==this.Se?k5(9):2==this.Se&&k5(10);var a=this.g;a.Jf=this.Fg;B5(a,2)}};
g.h.mn=function(){return this.g.mn()};
g.h.isActive=function(){return this.g.isActive()};
g.h.uf=function(a){this.g.uf(a)};g.h=v5.prototype;g.h.El=null;g.h.ce=null;g.h.xc=null;g.h.Yt=null;g.h.Fo=null;g.h.yz=null;g.h.So=null;g.h.Tm=0;g.h.lP=0;g.h.yd=null;g.h.kh=null;g.h.tg=null;g.h.fi=null;g.h.eh=null;g.h.qr=null;g.h.Uj=-1;g.h.VB=-1;g.h.Jf=-1;g.h.tj=0;g.h.lj=0;g.h.ci=8;var C5=new g.ag;g.B(SBa,g.Af);g.B(TBa,g.Af);g.B(UBa,g.Af);g.h=v5.prototype;g.h.connect=function(a,b,c,d,e){k5(0);this.Yt=b;this.El=c||{};d&&g.za(e)&&(this.El.OSID=d,this.El.OAID=e);this.C?(p5((0,g.A)(this.Rz,this,a),100),YBa(this)):this.Rz(a)};
g.h.Rz=function(a){this.eh=new PBa(this);this.eh.Zt=null;this.eh.l=this.B;this.eh.connect(a)};
g.h.eB=function(){return 0==this.g};
g.h.rE=function(a){this.kh=null;aCa(this,a)};
g.h.qE=function(){this.tg=null;this.xc=new g5(this,this.o,"rpc",this.D);this.xc.ri=null;this.xc.cu=0;var a=this.yz.clone();g.pn(a,"RID","rpc");g.pn(a,"SID",this.o);g.pn(a,"CI",this.qr?"0":"1");g.pn(a,"AID",this.Uj);w5(this,a);if(!g.Xd||g.Kc(10))g.pn(a,"TYPE","xmlhttp"),h5(this.xc,a,!0,this.So,!1);else{g.pn(a,"TYPE","html");var b=this.xc,c=!!this.So;b.Bj=3;b.qh=K4(a.clone());LBa(b,c)}};
g.h.lE=function(a,b){if(0!=this.g&&(this.xc==a||this.ce==a))if(this.Jf=a.dm,this.ce==a&&3==this.g)if(7<this.ci){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.tg){if(this.xc)if(this.xc.zk+3E3<this.ce.zk)y5(this),this.xc.cancel(),this.xc=null;else break a;A5(this);k5(19)}}else this.VB=c[1],0<this.VB-this.Uj&&37500>c[2]&&this.qr&&0==this.lj&&!this.fi&&(this.fi=p5((0,g.A)(this.PP,this),6E3));else B5(this,11)}else b!=wDa.rY.g&&B5(this,11);else if(this.xc==a&&
y5(this),!g.D(b)){c=this.B.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Uj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.So=e[2],e=e[3],null!=e?this.ci=e:this.ci=6,this.g=3,this.yd&&this.yd.Lz(),this.yz=s5(this,this.mn()?this.So:null,this.Yt),bCa(this)):"stop"==e[0]&&B5(this,7):3==this.g&&("stop"==e[0]?B5(this,7):"noop"!=e[0]&&this.yd&&this.yd.Kz(e),this.lj=0)}}};
g.h.PP=function(){null!=this.fi&&(this.fi=null,this.xc.cancel(),this.xc=null,A5(this),k5(20))};
g.h.bq=function(a){if(this.xc==a){y5(this);this.xc=null;var b=2}else if(this.ce==a)this.ce=null,b=1;else return;this.Jf=a.dm;if(0!=this.g)if(a.Af)1==b?(b=(0,g.G)()-a.zk,C5.dispatchEvent(new TBa(C5,a.Ri?a.Ri.length:0,b,this.tj)),x5(this),this.A.length=0):bCa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Jf)){if(d=1==b)this.ce||this.kh||1==this.g||2<=this.tj?d=!1:(this.kh=p5((0,g.A)(this.rE,this,a),cCa(this,this.tj)),this.tj++,d=!0);d=!(d||2==b&&A5(this))}if(d)switch(c){case 1:B5(this,
5);break;case 4:B5(this,10);break;case 3:B5(this,6);break;case 7:B5(this,12);break;default:B5(this,2)}}};
g.h.QJ=function(a){if(!g.Va(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.jV=function(a){a?k5(2):(k5(1),dCa(this,8))};
g.h.qt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Qx;a.F=!1;return a};
g.h.isActive=function(){return!!this.yd&&this.yd.isActive(this)};
g.h.uf=function(a){C5.dispatchEvent(new UBa(C5,a))};
g.h.mn=function(){return!(!g.Xd||g.Kc(10))};
g.h=eCa.prototype;g.h.Lz=function(){};
g.h.Kz=function(){};
g.h.Jz=function(){};
g.h.Ts=function(){};
g.h.KA=function(){return{}};
g.h.isActive=function(){return!0};g.B(D5,g.J);g.h=D5.prototype;g.h.lT=function(){this.zd=Math.min(3E5,2*this.zd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.zd+15E3*Math.random();g.Ou(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.zd=5E3};g.B(E5,eCa);g.h=E5.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.ak=function(a){return this.o.si(a)};
g.h.T=function(a,b){return this.o.T.apply(this.o,arguments)};
g.h.dispose=function(){this.zb||(this.zb=!0,g.yf(this.o),hCa(this),g.yf(this.l),this.l=null)};
g.h.ia=function(){return this.zb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.I+"/test";b=this.I+"/bind";var d=new v5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.J),e=this.g;e&&(e.yd=null);d.yd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Uj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):F5(this)&&ZBa(this.g,c)};
g.h.Lz=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)ZBa(this.g,a[b])}this.T("handlerOpened")};
g.h.Jz=function(a){var b=2==a&&401==this.g.Jf;4==a||b||this.l.start();this.T("handlerError",a)};
g.h.Ts=function(a){if(!this.l.isActive())this.T("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.KA=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.fc(a,this.B);return a};
g.h.Kz=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),XBa(this.g)):this.T("handlerMessage",new fCa(a[0],a[1]))};
g.h.LV=function(){this.l.isActive();var a=this.g,b=0;a.xc&&b++;a.ce&&b++;0!=b||this.connect(this.B,this.A)};G5.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G5.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
G5.prototype.B=function(a){a(Error("request timed out"))};var pCa=(0,g.G)(),J5=null,M5=Array(50),L5=-1,N5=!1;g.B(O5,g.V);O5.prototype.re=function(){return this.g};
O5.prototype.contains=function(a){return!!T4(this.g,a)};
O5.prototype.get=function(a){return a?U4(this.g,a):null};
O5.prototype.info=function(a){K5(this.D,a)};g.B(P5,g.V);var xDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=P5.prototype;g.h.start=function(){!this.g&&isNaN(this.Ga)&&this.xG()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Ga)||(g.GE(this.Ga),this.Ga=NaN)};
g.h.V=function(){this.stop();P5.ea.V.call(this)};
g.h.xG=function(){this.Ga=NaN;this.g=g.pF(H5(this.C,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.NV,this),onError:(0,g.A)(this.MV,this),Dd:(0,g.A)(this.OV,this)})};
g.h.NV=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.T("pairingComplete",new O4(c))};
g.h.MV=function(a){this.g=null;a.status&&404==a.status?this.l>=xDa.length?this.T("pairingFailed",Error("DIAL polling timed out")):(a=xDa[this.l],this.Ga=g.EE((0,g.A)(this.xG,this),a),this.l++):this.T("pairingFailed",Error("Server error "+a.status))};
g.h.OV=function(){this.g=null;this.T("pairingFailed",Error("Server not responding"))};g.B(R5,O5);g.h=R5.prototype;g.h.start=function(){Q5(this)&&this.T("screenChange");!g.WH("yt-remote-lounge-token-expiration")&&tCa(this);g.GE(this.l);this.l=g.EE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){Q5(this);qCa(this,a);S5(this,!1);this.T("screenChange");b(a);a.token||tCa(this)};
g.h.remove=function(a,b){var c=Q5(this);sCa(this,a)&&(S5(this,!1),c=!0);b(a);c&&this.T("screenChange")};
g.h.ir=function(a,b,c,d){var e=Q5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.T("screenChange")};
g.h.V=function(){g.GE(this.l);R5.ea.V.call(this)};
g.h.zK=function(a){Q5(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S5(this,!b);b&&K5(this.D,"Missed "+b+" lounge tokens.")};
g.h.yK=function(a){K5(this.D,"Requesting lounge tokens failed: "+a)};g.B(U5,g.V);g.h=U5.prototype;g.h.start=function(){var a=parseInt(g.WH("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?W5(this):(this.A=(0,g.G)()+3E5,g.VH("yt-remote-fast-check-period",this.A),this.Jw())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){T5("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!U4(a,d)},this);
V5(this,b)};
g.h.V=function(){g.GE(this.o);this.o=NaN;this.l&&(this.l.abort(),this.l=null);U5.ea.V.call(this)};
g.h.Jw=function(){g.GE(this.o);this.o=NaN;this.l&&this.l.abort();var a=wCa(this);if(g.Pb(a)){var b=H5(this.B,"/pairing/get_screen_availability");this.l=I5(this.B,b,{lounge_token:g.Sb(a).join(",")},(0,g.A)(this.SS,this,a),(0,g.A)(this.RS,this))}else V5(this,{}),W5(this)};
g.h.SS=function(a,b){this.l=null;var c=g.Sb(wCa(this));if(g.pb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V5(this,d);W5(this)}else this.oc("Changing Screen set during request."),this.Jw()};
g.h.RS=function(a){this.oc("Screen availability failed: "+a);this.l=null;W5(this)};
g.h.oc=function(a){K5("OnlineScreenService",a)};g.B(X5,O5);g.h=X5.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.T("screenChange"),this.l.isEmpty()||this.T("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.ir=function(a,b,c,d){this.o.contains(a)?this.o.ir(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K5(this.D,a),d(Error(a)))};
g.h.re=function(a){return a?this.g:g.cb(this.g,(0,g.ke)(this.A,function(a){return!this.contains(a)},this))};
g.h.yG=function(){return(0,g.ke)(this.re(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.zG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new P5(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.yf(f);d(Y5(this,a))},this));
f.subscribe("pairingFailed",function(a){g.yf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.QV=function(a,b,c,d){g.pF(H5(this.C,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new O4(d.screen||{});if(!e.name||ACa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);ACa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(Y5(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Dd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.yf(this.o);g.yf(this.l);X5.ea.V.call(this)};
g.h.MK=function(){BCa(this);this.T("screenChange");this.l.update()};
X5.prototype.dispose=X5.prototype.dispose;g.B($5,g.V);g.h=$5.prototype;g.h.cq=function(a){this.o=a;this.T("sessionScreen",this.o)};
g.h.xe=function(a){this.ia()||(a&&a6(this,""+a),this.o=null,this.T("sessionScreen",null))};
g.h.info=function(a){K5(this.O,a)};
g.h.BG=function(){return null};
g.h.Vw=function(a){var b=this.l;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){a6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.Vw("");$5.ea.V.call(this)};g.B(b6,$5);g.h=b6.prototype;g.h.Uw=function(a){if(this.g){if(this.g==a)return;a6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);DCa(this)};
g.h.Wj=function(a){this.info("launchWithParams no-op for Cast: "+g.Rg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.xe()},this),(0,g.A)(function(){this.xe(Error("Failed to stop receiver app."))},this)):this.xe(Error("Stopping cast device witout session."))};
g.h.Vw=g.y;g.h.V=function(){this.info("disposeInternal");g.GE(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;b6.ea.V.call(this)};
g.h.ZT=function(a,b){if(!this.ia())if(b){var c=g.Lx(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Rg(c));switch(d){case "mdxSessionStatus":CCa(this,c.screenId);break;default:a6(this,"Unknown youtube message: "+d)}}else a6(this,"Unable to parse message.")}else a6(this,"No data in message.")};
g.h.VA=function(a,b,c,d){zCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(a6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.EE((0,g.A)(this.VA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.BG=function(){return this.g};
g.h.RV=function(a){this.ia()||a||(a6(this,"Cast session died."),this.xe())};g.B(c6,$5);g.h=c6.prototype;g.h.Uw=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.Wj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.GE(this.C);this.A?this.A.stop((0,g.A)(this.xe,this,null),(0,g.A)(this.xe,this,"Failed to stop DIAL device.")):this.xe()};
g.h.V=function(){this.g();this.g=g.y;g.GE(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;c6.ea.V.call(this)};
g.h.UV=function(a){this.ia()||a||(a6(this,"DIAL session died."),this.g(),this.g=g.y,this.xe())};
g.h.Eu=function(a){this.I=S4();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,FCa(this));a(b);ECa(this)}else this.D=(0,g.A)(function(){g.GE(this.C);this.D=g.y;this.C=NaN;var b=new chrome.cast.DialLaunchResponse(!0,FCa(this));a(b);ECa(this)},this),this.C=g.EE((0,g.A)(function(){this.D()},this),100)};
g.h.ZL=function(a,b,c){zCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.cq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.Eu(b,c)},this),(0,g.A)(function(a){a6(this,"Failed to get DIAL screen: "+a);
this.Eu(b,c)},this))};g.B(d6,$5);d6.prototype.stop=function(){this.xe()};
d6.prototype.Uw=g.y;d6.prototype.Wj=function(){g.GE(this.g);this.g=NaN;var a=U4(this.H.re(),this.l.label);a?this.cq(a):this.xe(Error("No such screen"))};
d6.prototype.V=function(){g.GE(this.g);this.g=NaN;d6.ea.V.call(this)};g.B(e6,g.V);g.h=e6.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.nE,this),(0,g.A)(this.AS,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.xQ,this);chrome.cast.initialize(c,(0,g.A)(function(){this.ia()||
(chrome.cast.addReceiverActionListener(this.A),mCa(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.AG,this)),this.o=HCa(this),chrome.cast.setCustomReceivers(this.o,g.y,(0,g.A)(function(a){this.oc("Failed to set initial custom receivers: "+g.Rg(a))},this)),this.T("yt-remote-cast2-availability-change",g6(this)),b(!0))},this),(0,g.A)(function(a){this.oc("Failed to initialize API: "+g.Rg(a));
b(!1)},this))};
g.h.RU=function(a,b){f6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)f6("Unsetting old screen status: "+this.g.l.friendlyName),h6(this,null)}if(a&&b){if(!this.g){c=U4(this.l.re(),a);if(!c){f6("setConnectedScreenStatus: Unknown screen.");return}var d=GCa(this,c);d||(f6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.o.push(d),chrome.cast.setCustomReceivers(this.o,
g.y,(0,g.A)(function(a){this.oc("Failed to set initial custom receivers: "+g.Rg(a))},this)));
f6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);h6(this,new d6(this.l,d),!0)}this.g.Vw(b)}else f6("setConnectedScreenStatus: no screen.")};
g.h.SU=function(a){this.ia()?this.oc("Setting connection data on disposed cast v2"):this.g?this.g.Wj(a):this.oc("Setting connection data without a session")};
g.h.TV=function(){this.ia()?this.oc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),h6(this,null)):f6("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.nE,this),(0,g.A)(this.XS,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.AG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);g.$a(g.w("yt.mdx.remote.debug.handlers_")||[],jCa);g.yf(this.g);e6.ea.V.call(this)};
g.h.oc=function(a){K5("Controller",a)};
g.h.oE=function(a,b){this.g==a&&(b||h6(this,null),this.T("yt-remote-cast2-session-change",b))};
g.h.wS=function(a,b){if(!this.ia())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),f6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)f6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{f6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.T("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:h6(this,
new d6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:h6(this,new c6(this.l,a,this.C));break;case chrome.cast.ReceiverType.CAST:h6(this,new b6(this.l,a));break;default:this.oc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.oc("Stopping receiver w/o session: "+a.friendlyName)}else this.oc("onReceiverAction_ called without receiver.")};
g.h.xQ=function(a){if(this.ia())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.oc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.oc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.o)return f6("Reselecting dial screen."),
this.T("yt-remote-cast2-session-change",this.g.o),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.oc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);h6(this,new c6(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.ZL,b,(b.F.extraData||{}).screenId||null)):new Promise((0,g.A)(b.Eu,b))};
g.h.nE=function(a){if(!this.ia()){f6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)f6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),h6(this,new b6(this.l,b),!0);else{this.oc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=U4(this.l.re(),c.label);d&&P4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(f6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.yf(this.g),this.g=new b6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.oE,this,this.g)),this.g.Wj(null));this.g.Uw(a)}}};
g.h.SV=function(){return this.g?this.g.BG():null};
g.h.XS=function(a){this.ia()||(this.oc("Failed to estabilish a session: "+g.Rg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&h6(this,null))};
g.h.AS=function(a){f6("Receiver availability updated: "+a);if(!this.ia()){var b=g6(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;g6(this)!=b&&this.T("yt-remote-cast2-availability-change",g6(this))}};
g.h.AG=function(){this.ia()||(this.o=HCa(this),f6("Updating custom receivers: "+g.Rg(this.o)),chrome.cast.setCustomReceivers(this.o,g.y,(0,g.A)(function(){this.oc("Failed to set custom receivers.")},this)),this.T("yt-remote-cast2-availability-change",g6(this)))};
e6.prototype.setLaunchParams=e6.prototype.SU;e6.prototype.setConnectedScreenStatus=e6.prototype.RU;e6.prototype.stopSession=e6.prototype.TV;e6.prototype.getCastSession=e6.prototype.SV;e6.prototype.requestSession=e6.prototype.requestSession;e6.prototype.init=e6.prototype.init;e6.prototype.dispose=e6.prototype.dispose;var n6=[];g.h=s6.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";t6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Nf=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.l=a.seekableEnd,this.F=a.duration,this.H=a.loadedTime,this.o=a.liveIngestionTime,this.B=!isNaN(this.o))};
g.h.rb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.B?this.F+u6(this):this.F};
g.h.clone=function(){return new s6(y6(this))};g.B(A6,g.V);g.h=A6.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,G6(this,"play")):F6(this,"play"),E6(this,1,w6(B6(this))),this.T("remotePlayerChange")):C6(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,G6(this,"pause")):F6(this,"pause"),E6(this,2,w6(B6(this))),this.T("remotePlayerChange")):C6(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.l){var b=B6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.rb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,G6(this,"seekTo",{newTime:a}))}else F6(this,"seekTo",{newTime:a});E6(this,3,a);this.T("remotePlayerChange")}else C6(this,g.La(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,G6(this,"stopVideo")):F6(this,"stopVideo");var a=B6(this);a.index=-1;a.videoId="";t6(a);D6(this,a);this.T("remotePlayerChange")}else C6(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=B6(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){K5("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.oc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){K5("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.oc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F6(this,"setVolume",e)}c.muted=b;c.volume=a;D6(this,c)}else C6(this,g.La(this.setVolume,a,b))};
g.h.zF=function(a,b){if(1==this.g){var c=B6(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Rg(b.style),g.fc(d,c.g));F6(this,"setSubtitlesTrack",d);D6(this,c)}else C6(this,g.La(this.zF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){F6(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lb.id});var c=B6(this);c.audioTrackId=b.Lb.id;D6(this,c)}else C6(this,g.La(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=B6(this);c=c||0;var m={videoId:a,currentIndex:c};x6(l,a,c);g.za(b)&&(v6(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Rg(k));F6(this,"setPlaylist",m);d||D6(this,l)};
g.h.jq=function(a,b){if(1==this.g){if(a&&b){var c=B6(this);x6(c,a,b);D6(this,c)}F6(this,"previous")}else C6(this,g.La(this.jq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=B6(this);x6(c,a,b);D6(this,c)}F6(this,"next")}else C6(this,g.La(this.nextVideo,a,b))};
g.h.lA=function(){1==this.g?F6(this,"dismissAutoplay"):C6(this,this.lA)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.T("proxyStateChange",a,this.g)}A6.ea.dispose.call(this)};
g.h.V=function(){UCa(this);this.A=null;this.B.clear();z6(this,null);A6.ea.V.call(this)};
g.h.Wx=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.T("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.dD(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.rS=function(a,b){this.T(a,b)};
g.h.WP=function(a){if(!a)this.Wm(null),z6(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=B6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D6(this,b)}};
g.h.Wm=function(a){K5("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),VCa(this),this.T("remotePlayerChange")};
g.h.VP=function(a){a?(VCa(this),this.T("remotePlayerChange")):this.Wm(null)};
g.h.mx=function(){F6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.iQ=function(){var a=RCa();a&&z6(this,a)};
g.h.oc=function(a){K5("CP",a)};g.B(H6,g.V);g.h=H6.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.gb.listId=c);this.gb.videoId=d;this.gb.index=k||0;this.gb.state=3;v6(this.gb,m);this.A="UNSUPPORTED";I6("Connecting with setPlaylist and params: "+g.Rg(l));this.g.connect({method:"setPlaylist",
params:g.Rg(l)},a,tBa())}else I6("Connecting without params"),this.g.connect({},a,tBa());XCa(this)};
g.h.dispose=function(){this.ia()||(this.T("beforeDispose"),J6(this,3));H6.ea.dispose.call(this)};
g.h.V=function(){K6(this);M6(this);L6(this);g.GE(this.H);this.H=NaN;g.GE(this.I);this.I=NaN;this.o=null;g.sG(this.R);this.R.length=0;this.g.dispose();H6.ea.V.call(this);this.A=this.D=this.l=this.gb=this.g=null};
g.h.pK=function(){this.C(2)};
g.h.aQ=function(){I6("Channel opened");this.L&&(this.L=!1,L6(this),this.O=g.EE((0,g.A)(function(){I6("Timing out waiting for a screen.");this.C(1)},this),15E3));
xBa(gCa(this.g),this.Y)};
g.h.XP=function(){I6("Channel closed");isNaN(this.B)?Z4(!0):Z4();this.dispose()};
g.h.YP=function(a){Z4();isNaN(this.F())?(I6("Channel error: "+a+" without reconnection"),this.dispose()):(this.L=!0,I6("Channel error: "+a+" with reconnection in "+this.F()+" ms"),J6(this,2))};
g.h.ZP=function(a){a.params?I6("Received: action="+a.action+", params="+g.Rg(a.params)):I6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Lx(a.params.devices);this.l=(0,g.I)(a,function(a){return new N4(a)});
a=!!g.Ra(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
$Ca(this,a);break;case "loungeScreenDisconnected":g.ab(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
$Ca(this,!1);break;case "remoteConnected":var b=new N4(g.Lx(a.params.device));g.Ra(this.l,function(a){return b?a.id==b.id:!1})||g.Ya(this.l,b);
break;case "remoteDisconnected":b=new N4(g.Lx(a.params.device));g.ab(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":bDa(this,a);break;case "nowPlaying":dDa(this,a);break;case "onStateChange":cDa(this,a);break;case "onAdStateChange":eDa(this,a);break;case "onVolumeChanged":fDa(this,a);break;case "onSubtitlesTrackChanged":aDa(this,a);break;case "nowAutoplaying":gDa(this,a);break;case "autoplayDismissed":this.T("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.T("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.T("autoplayModeChange",this.A);"DISABLED"==this.A&&this.T("autoplayDismissed");break;case "onHasPreviousNextChanged":hDa(this,a);break;case "requestAssistedSignIn":this.T("assistedSignInRequested",a.params.authCode);break;default:I6("Unrecognized action: "+a.action)}};
g.h.AU=function(){if(this.o){var a=this.o;this.o=null;this.gb.videoId!=a&&N6(this,"getNowPlaying")}};
H6.prototype.subscribe=H6.prototype.subscribe;H6.prototype.unsubscribeByKey=H6.prototype.ak;H6.prototype.fa=function(){var a=3;this.ia()||(a=0,isNaN(this.F())?F5(this.g)&&isNaN(this.B)&&(a=1):a=2);return a};
H6.prototype.getProxyState=H6.prototype.fa;H6.prototype.C=function(a){I6("Disconnecting with "+a);K6(this);this.T("beforeDisconnect",a);1==a&&Z4();hCa(this.g,a);this.dispose()};
H6.prototype.disconnect=H6.prototype.C;H6.prototype.da=function(){var a=this.gb;this.o&&(a=this.gb.clone(),x6(a,this.o,a.index));return y6(a)};
H6.prototype.getPlayerContextData=H6.prototype.da;
H6.prototype.la=function(a){var b=new s6(a);b.videoId&&b.videoId!=this.gb.videoId&&(this.o=b.videoId,g.GE(this.H),this.H=g.EE((0,g.A)(this.AU,this),5E3));var c=[];this.gb.listId==b.listId&&this.gb.videoId==b.videoId&&this.gb.index==b.index||c.push("remoteQueueChange");this.gb.playerState==b.playerState&&this.gb.volume==b.volume&&this.gb.muted==b.muted&&w6(this.gb)==w6(b)&&g.Rg(this.gb.g)==g.Rg(b.g)||c.push("remotePlayerChange");this.gb.reset(a);(0,g.C)(c,function(a){this.T(a)},this)};
H6.prototype.setPlayerContextData=H6.prototype.la;H6.prototype.X=function(){var a=this.g.C.id,b=g.Ra(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
H6.prototype.getOtherConnectedRemoteId=H6.prototype.X;H6.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():NaN};
H6.prototype.getReconnectTimeout=H6.prototype.F;H6.prototype.ca=function(){return this.A||"UNSUPPORTED"};
H6.prototype.getAutoplayMode=H6.prototype.ca;H6.prototype.ba=function(){return this.D||""};
H6.prototype.getAutoplayVideoId=H6.prototype.ba;H6.prototype.wa=function(){if(!isNaN(this.F())){var a=this.g.l;g.Pu(a.g);a.start()}};
H6.prototype.reconnect=H6.prototype.wa;H6.prototype.ha=function(a,b){N6(this,a,b);ZCa(this)};
H6.prototype.sendMessage=H6.prototype.ha;g.B(O6,O5);g.h=O6.prototype;g.h.re=function(a){return this.hd.$_gs(a)};
g.h.contains=function(a){return!!this.hd.$_c(a)};
g.h.get=function(a){return this.hd.$_g(a)};
g.h.start=function(){this.hd.$_st()};
g.h.add=function(a,b,c){this.hd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.hd.$_r(a,b,c)};
g.h.ir=function(a,b,c,d){this.hd.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.hd.$_ubk(this.l[a]);this.l.length=0;this.hd=null;O6.ea.V.call(this)};
g.h.PV=function(){this.T("screenChange")};
g.h.RR=function(){this.T("onlineScreenChange")};
X5.prototype.$_st=X5.prototype.start;X5.prototype.$_gspc=X5.prototype.QV;X5.prototype.$_gsppc=X5.prototype.zG;X5.prototype.$_c=X5.prototype.contains;X5.prototype.$_g=X5.prototype.get;X5.prototype.$_a=X5.prototype.add;X5.prototype.$_un=X5.prototype.ir;X5.prototype.$_r=X5.prototype.remove;X5.prototype.$_gs=X5.prototype.re;X5.prototype.$_gos=X5.prototype.yG;X5.prototype.$_s=X5.prototype.subscribe;X5.prototype.$_ubk=X5.prototype.ak;var P6=null,Q6=null,e7=null,U6=[];g.r(f7,g.J);g.h=f7.prototype;
g.h.V=function(){g.J.prototype.V.call(this);this.A.stop();this.C.stop();this.J.stop();this.L();this.g.unsubscribe("proxyStateChange",this.kE,this);this.g.unsubscribe("remotePlayerChange",this.Zm,this);this.g.unsubscribe("remoteQueueChange",this.eq,this);this.g.unsubscribe("autoplayUpNext",this.HD,this);this.g.unsubscribe("previousNextChange",this.hE,this);this.g.unsubscribe("nowAutoplaying",this.ZD,this);this.g.unsubscribe("autoplayDismissed",this.GD,this);this.g=this.B=null};
g.h.JC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i7(this)){if(!B6(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":B6(this.g).rb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Wl(c[0],c[1]);break;case "control_subtitles_set_track":j7(this,c[0]);break;case "control_set_audio_track":c=c[0],i7(this)&&this.g.setAudioTrack(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();k7(this,0==c?void 0:c);break;case "control_seek":k7(this,c[0]);break;case "control_subtitles_set_track":j7(this,c[0]);break;case "control_set_audio_track":c=c[0],i7(this)&&this.g.setAudioTrack(this.l.getVideoData(1).videoId,c)}};
g.h.UP=function(a){this.J.kK(a)};
g.h.tV=function(a){this.JC("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.PF=function(){var a=this.l.getOption("captions","track");g.Yb(a)||j7(this,a)};
g.h.VD=function(a){if(i7(this)){this.g.unsubscribe("remotePlayerChange",this.Zm,this);var b=Math.round(a.volume);a=!!a.muted;var c=B6(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.O.start();this.g.subscribe("remotePlayerChange",this.Zm,this)}};
g.h.lR=function(){g.Yb(this.D)||tDa(this,this.D);this.F=!1};
g.h.kE=function(a,b){this.C.stop();2==b&&this.NF()};
g.h.Zm=function(){if(i7(this)){this.A.stop();var a=B6(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Dk(1);break;case 1082:case 1083:this.B.Dk(0);break;default:this.B.Dk(-1)}switch(a.playerState){case 1081:case 1:h7(this,new g.mR(8));this.MF();break;case 1085:case 3:h7(this,new g.mR(9));break;case 1083:case 0:h7(this,new g.mR(2));this.I.stop();g7(this,this.l.getVideoData().lengthSeconds);break;case 1084:h7(this,new g.mR(4));break;case 2:h7(this,new g.mR(4));g7(this,w6(a));
break;case -1:h7(this,new g.mR(64));break;case -1E3:h7(this,new g.mR(128,{errorCode:"mdx.remoteerror",message:"\u6b64\u89c6\u9891\u65e0\u6cd5\u8fdc\u7a0b\u64ad\u653e\u3002"}))}a=B6(this.g).g;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,tDa(this,a));a=B6(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.O.isActive()||this.nG()}else sDa(this)};
g.h.hE=function(){this.l.T("mdxpreviousnextchange")};
g.h.eq=function(){i7(this)||sDa(this)};
g.h.sJ=function(){this.g.lA()};
g.h.HD=function(a){a&&(a=g.pF("/watch_queue_ajax",{method:"GET",cd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.xT,this)}))&&(this.L=(0,g.A)(a.abort,a))};
g.h.xT=function(a,b){var c=new g.tP(g.Y(this.l),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.T("mdxautoplayupnext",c)};
g.h.ZD=function(a){isNaN(a)||this.l.T("mdxnowautoplaying",a)};
g.h.GD=function(){this.l.T("mdxautoplaycanceled")};
g.h.ON=function(a,b){-1==B6(this.g).playerState?k7(this,a):b&&this.g.seekTo(a)};
g.h.nG=function(){if(i7(this)){var a=B6(this.g);this.o.Ja(this.R);a.muted?this.l.mute():this.l.unMute();this.l.setVolume(a.volume);this.R=this.o.N(this.l,"onVolumeChange",this.VD)}};
g.h.MF=function(){this.A.stop();if(!this.g.ia()){var a=B6(this.g);a.rb()&&h7(this,new g.mR(8));g7(this,w6(a));this.A.start()}};
g.h.NF=function(){this.C.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.C.start()};g.r(l7,g.W);l7.prototype.B=function(a){vDa(this,a.state)};g.r(m7,g.VW);m7.prototype.J=function(){var a=this.o.getOption("remote","receivers");a&&1<a.length&&!this.o.getOption("remote","quickCast")?(this.H=g.rb(a,this.C,this),g.WW(this,(0,g.I)(a,this.C)),a=this.o.getOption("remote","currentReceiver"),this.cg(this.C(a)),this.enable(!0)):this.enable(!1)};
m7.prototype.C=function(a){return a.key};
m7.prototype.Ye=function(a){return"cast-selector-receiver"==a?"\u6295\u5c04\u2026":this.H[a].name};
m7.prototype.Bd=function(a){g.VW.prototype.Bd.call(this,a);this.o.setOption("remote","currentReceiver",this.H[a]);this.A.Ib()};g.r(n7,g.PV);g.h=n7.prototype;g.h.create=function(){mDa(g.jN(g.Y(this.player)));this.B.push(g.LE("yt-remote-before-disconnect",this.QP,this));this.B.push(g.LE("yt-remote-connection-change",this.BS,this));this.B.push(g.LE("yt-remote-receiver-availability-change",this.iE,this));this.B.push(g.LE("yt-remote-auto-connect",this.zS,this));this.B.push(g.LE("yt-remote-receiver-resumed",this.yS,this));this.iE()};
g.h.load=function(){this.player.cancelPlayback();g.PV.prototype.load.call(this);this.A=new f7(this,this.player,this.g);var a=(a=rDa())?a.currentTime:0;var b=d7()?new A6(Z6(),void 0):null;0==a&&b&&(a=w6(B6(b)));0!=a&&this.Be(a);uDa(this,this.Lm,this.Lm);g.g_(this.player.app,6)};
g.h.unload=function(){this.player.T("mdxautoplaycanceled");this.o=this.l;g.zf(this.A,this.g);this.g=this.A=null;g.PV.prototype.unload.call(this);g.g_(this.player.app,5)};
g.h.V=function(){g.ME(this.B);g.PV.prototype.V.call(this)};
g.h.Jh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.JC.apply(this.A,[a].concat(g.ea(c)))};
g.h.Dk=function(a){this.F=a};
g.h.getAdState=function(){return this.F};
g.h.gK=function(){return this.loaded?this.A.suggestion:null};
g.h.Nf=function(){return this.g?B6(this.g).Nf:!1};
g.h.hasNext=function(){return this.g?B6(this.g).hasNext:!1};
g.h.Be=function(a,b){this.H=a||0;this.player.T("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=B6(this.g),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.g("web_player_mdx_allow_seeking_change_killswitch")?this.player.Kc():!a.isAdPlaying()&&this.player.Kc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.o+u6(a):a.o,isPeggedToLive:1>=(a.B?a.l+u6(a):a.l)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.l+u6(a):a.l,seekableStart:0<a.A?a.A+
u6(a):a.A}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.jq=function(){this.g&&this.g.jq()};
g.h.QP=function(a){1==a&&(this.D=this.g?B6(this.g):null)};
g.h.BS=function(){var a=d7()?new A6(Z6(),void 0):null;if(a){var b=this.o;this.loaded&&this.unload();this.g=a;this.D=null;b.key!=this.l.key&&(this.o=b,this.load())}else g.yf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.D)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,w6(a)));this.player.T("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.iE=function(){this.C=[this.l].concat(oDa());var a=$6()||this.l;o7(this,a);this.player.ya("onMdxReceiversChange")};
g.h.zS=function(){var a=$6();o7(this,a)};
g.h.yS=function(){this.o=$6()};
g.h.Hc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.C;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?q6():o7(this,b)),this.loaded?this.o:this.l;case "quickCast":return 2==this.C.length&&"cast-selector-receiver"==this.C[1].key?(b&&q6(),!0):!1}};
g.h.mx=function(){this.g.mx()};
g.h.tc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.iZ.remote=n7;})(_yt_player);
